In [4]:
import sys
import numpy as np

In [5]:
li_arr=[i for i in range(100)]
np_arr=np.arange(100)
print(np_arr.itemsize)
print(sys.getsizeof(li_arr[0]))

4
24


In [6]:
a=[1,2,3]
b=np.array(a)
print(b)

[1 2 3]


In [10]:
print(np.ones(4))

[1. 1. 1. 1.]


In [9]:
print(np.ones(4,dtype=int))

[1 1 1 1]


In [13]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [14]:
a = np.empty(4, dtype = int)
print(a)


[6 6 6 6]


In [12]:
print(np.full(4,6))# size and value

[6 6 6 6]


In [11]:
print(np.empty(4))

[1. 1. 1. 1.]


In [15]:
np.random.rand()

0.06316708353783074

In [16]:
np.random.randint(10, 4)

ValueError: low >= high

In [40]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
print(*input_[2,:3])
print(*input_[1:4,3])
p=input_[2:]
print(*p[0],end=" ")
print(*p[1])
q=input_[1:3,1:3]
print(*q[0],end=" ")
print(*q[1])

11 12 13
9 14 19
11 12 13 14 15 16 17 18 19 20
7 8 12 13
